/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_descriptor_value_changed       21
#define gattdb_humidity                       24
#define gattdb_es_measurement_humidity        26
#define gattdb_es_trigger_setting_humidity    27
#define gattdb_es_configuration_humidity      28
#define gattdb_characteristic_user_description_humidity 29
#define gattdb_valid_range_humdity            30
#define gattdb_pressure                       32
#define gattdb_es_measurement_pressure        34
#define gattdb_es_trigger_setting_pressure    35
#define gattdb_es_configuration_pressure      36
#define gattdb_characteristic_user_description_pressure 37
#define gattdb_valid_range_pressure_pressure  38
#define gattdb_temperature                    40
#define gattdb_es_measurement_temp            42
#define gattdb_es_trigger_setting_temp        43
#define gattdb_es_configuration_temp          44
#define gattdb_characteristic_user_description_temp 45
#define gattdb_valid_range_temp               46
#define gattdb_elevation                      48
#define gattdb_es_measurement                 50
#define gattdb_es_trigger_setting             51
#define gattdb_es_configuration               52
#define gattdb_characteristic_user_description 53
#define gattdb_valid_range                    54
#define gattdb_battery_level                  57
#define gattdb_characteristic_presentation_format 58
#define gattdb_ota_control                    61


#endif // __GATT_DB_H
