/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_daily_step_count               21
#define gattdb_client_notification_count      24
#define gattdb_alert_level                    29
#define gattdb_descriptor_value_changed       32
#define gattdb_elevation                      35
#define gattdb_humidity                       37
#define gattdb_pressure                       39
#define gattdb_temperature                    41
#define gattdb_battery_level                  44
#define gattdb_characteristic_presentation_format 46
#define gattdb_ota_control                    49


#endif // __GATT_DB_H
